[package]
name = "datafusion-quickstart"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion = { version = "40.0.0" }
tokio = { version = "^1.43", features = ["rt-multi-thread"] }
snmalloc-rs = "0.3"

[profile.release]
lto = true
codegen-units = 1